Add excluding argument for importlib.set_lazy_imports
Summary:

Add an optional argument `excluding` for `importlib.set_lazy_imports`.

Test Plan:

`excluding` is an optional argument for importlib.set_lazy_imports(). It can only accept an object which has `__contains__` attribute. Also, all the modules imported in the excluded module need to be eagerly loaded.

For example, let us have a module called `foo.py`.
```
import bar
```

If we call  `importlib.set_lazy_imports(excluding=["foo"])`, two actions will be executed at this moment.
1. Enable Lazy Imports from now
2. `foo` is marked as eagerly loaded in the future

That is, if we `import foo` and run `foo`, it will load `importlib` and `bar` at the same time.
However, `excluding` only marks modules as **shallow** eager imports. If `import baz` is in `bar.py`, `baz` will not be loaded.

Create `foo.py`, `bar.py`, and `baz.py` under the same path of `./python`.
```
print("I'm foooooo.")
import importlib
import bar

if not importlib.is_lazy_import(globals(), "bar"):
    print("bar is eager")
else:
    print("bar is lazy")
```
```
print("I'm bar!")
import baz
```
```
print("I'm baz")
```

No matter we starts Python with or without `-L`, the expected results are the same in the following tests.

```
$ ./python
>>> import importlib
>>> importlib.set_lazy_imports(excluding=["foo"])
>>> import foo
>>> importlib.is_lazy_import(globals(), "foo")
True
>>> foo
I'm foooooo.
I'm bar!
bar is eager
<module 'foo' from '/data/users/harperlin/cinder/foo.py'>
>>> importlib.is_lazy_import(globals(), "foo")
False
```

- Test 1:
```
$ ./python
>>> import importlib
>>> class MyClass:
...     def filter(self, name):
...         return name == "foo"
...     def __contains__(self, name):
...         return self.filter(name)
...
>>>
>>> cb = MyClass()
>>> importlib.set_lazy_imports(cb)
>>>
>>> import foo
>>> foo
I'm foooooo.
I'm bar!
bar is eager
<module 'foo' from '/data/users/harperlin/cinder/foo.py'>
```
- Test 2:
```
$ ./python
>>> import importlib
>>> class Checker:
... 	def __contains__(self, name):
... 		return name in ["test", "foo"]
...
>>> ck = Checker()
>>> importlib.set_lazy_imports(ck)
>>> import foo
>>> foo
I'm foooooo.
I'm bar!
bar is eager
<module 'foo' from '/data/users/harperlin/cinder/foo.py'>
```

```
$ ./python
>>> import importlib
>>> importlib.set_lazy_imports()
>>>
>>> import math
>>> importlib.is_lazy_import(globals(), "math")
True
>>> math.pi
3.141592653589793
>>> importlib.is_lazy_import(globals(), "math")
False
```

If we would like to change our `excluding` setting, we can run `set_lazy_imports` with the new `excluding` argument again like this example.

For example, run
```
$ ./python
>>> import importlib
```

Set the first `excluding` argument as the `Hello` object.
```
>>> class Hello:
... 	def filter(self, name):
... 		return name == "hello"
... 	def __contains__(self, name):
... 		return self.filter(name)
...
>>> cb1 = Hello()
>>> importlib.set_lazy_imports(cb1)
>>> import math
>>> importlib.is_lazy_import(globals(), "math")
True
>>> math.pi
3.141592653589793
>>> importlib.is_lazy_import(globals(), "math")
False
```

Correct the `excluding` argument by setting nothing.
```
importlib.set_lazy_imports()
```

Correct the `excluding` argument by using the `MyClass` object.
```
>>> class MyClass:
... 	def filter(self, name):
... 		return name == "foo"
... 	def __contains__(self, name):
... 		return self.filter(name)
...
>>> cb2 = MyClass()
>>> importlib.set_lazy_imports(cb2)
>>> import foo
>>> foo
I'm foooooo.
I'm bar!
bar is eager
<module 'foo' from '/data/users/harperlin/cinder/foo.py'>
>>> exit()
```

If the object used in `excluding` does not have `__contains__` , `set_lazy_imports` will raise `TypeError` and Lazy Imports will **NOT** be enabled.
```
$ ./python
>>> import importlib
>>> importlib.set_lazy_imports(123)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/users/harperlin/cinder/Lib/importlib/__init__.py", line 80, in set_lazy_imports
    _imp.set_lazy_imports(excluding)
TypeError: argument of type 'int' is not iterable
>>>
>>>
>>> def eager_foo(name):
...     return name == "foo"
...
>>> importlib.set_lazy_imports(eager_foo)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/users/harperlin/cinder/Lib/importlib/__init__.py", line 80, in set_lazy_imports
    _imp.set_lazy_imports(excluding)
TypeError: argument of type 'function' is not iterable
>>>
>>>
>>> import math
>>> importlib.is_lazy_import(globals(), "math")
False
```